name: proj2
channels:
    - pytorch
dependencies:
    - python==3.8
    - pip:
        - numpy==1.24.2
        - pybullet==3.2.5
        - gym==0.26.2
        - pyquaternion==0.9.9
        - tensorBoardX==2.6
        - scipy==1.10.1
        - mpi4py==3.1.4
        